### ISSUE TITLE
URL Routing Support (SPA)

### ISSUE THREAD

**Issue by Archmonger** [idom-team/idom-router#2]
### Current Situation

Currently, URL routes cannot be resolved within IDOM.

### Proposed Changes

Add support for URL routing within IDOM core.

### Implementation Details

Add [`React-Router`](https://reactrouter.com/) into IDOM core.

Here an example on how this can be implemented

```python
def route_component():
    http.browser_router(
        http.route("/"),
        http.route("path_1/"),
        http.route("path_2/")
    )
```

And here's [a reference video on explaining react-router.](https://www.youtube.com/watch?v=Law7wfdg_ls)

#### Things to be implemented
- `BrowserRouter`
   - Top level location to signify "this part of the code contains routing" 
- `Route`
   - This is where the actual URL path goes
   - React Router uses [some weird system for variables within URLs](https://v5.reactrouter.com/web/api/generatePath)
   - Instead of that, we can possibly support regex paths 
   - I'm a bit biased and I think [django's URL route matching](https://docs.djangoproject.com/en/4.0/topics/http/urls/#example) looks visually cleaner than regex though
   - Can possibly accept a kwarg of `regex: bool = False` to allow for regex routes?
- `Link`
   - Clicking on the contents of this changes the browser URL, but does not perform a HTTP refresh on the page 
   - Basically just a href with `prevent_default` pre-applied
   - Should accept a kwarg of `regex: bool = False` to allow for regex links
- `useHistory`
- `useLocation`
- `useParams`
- `useRouteMatch`

#### Things that might not need to be implemented
- `Routes` (formerly `Switch`)
   - In React, this is used to force matching ONLY ONE (first-most) path. 
   - In IDOM, this won't be needed if using a `match_all=False` kwarg within `browser_router`
- `NavLink`
   - It's just a link with extra styling. Doesn't really matter.
- `Redirect`
   - Doesn't need to exist if we just tell the user to use a regular HREF to do a HTTP page load. 
- `MemoryRouter`
   - Debug utility that isn't that important.
- `StaticRouter`
   - Used for server side rendering, which we don't have.
- `Prompt`
   - Just a pop-up asking whether you really want to navigate away from the page
   - This is useful but is way lower priority

**Comment by Archmonger** [comment]
Is this issue closable, since the initial package has been released?

Or are we keeping it open to track the development goals?

**Comment by rmorshea** [comment]
I think we can close this. Any features mentioned here that we should still implement can be created as separate issues.

**Comment by Archmonger** [comment]
Should we have a quick discussion on which of the "Things to be implemented" are worth moving forward with?

**Comment by bobwatcherx** [comment]
is there a complete example to do routing with reactpy_router and with navigation links

i get errror
```
root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/reactpy-router# python3 main.py 
Traceback (most recent call last):
  File "/home/miop/belajar/reactpy-router/main.py", line 2, in <module>
    import reactpy_router
  File "/home/miop/belajar/reactpy-router/reactpy_router/__init__.py", line 4, in <module>
    from . import simple
  File "/home/miop/belajar/reactpy-router/reactpy_router/simple.py", line 9, in <module>
    from reactpy_router.core import create_router
  File "/home/miop/belajar/reactpy-router/reactpy_router/core.py", line 117, in <module>
    module_from_file("reactpy-router", file=Path(__file__).parent / "bundle.js"),
  File "/usr/local/lib/python3.10/dist-packages/reactpy/web/module.py", line 196, in module_from_file
    raise FileNotFoundError(f"Source file does not exist: {source_file}")

```
```
from reactpy import component, html, run

from reactpy_router import Route, Link, bind



@component
def App():
    return html.h1("Hello, world!")


run(App)
```

**Comment by rmorshea** [comment]
Run this using a developer installation? I don't get this error if I just `pip install reactpy-router`.

**Comment by bobwatcherx** [comment]
i have installed with pip install reactpy-router .  but when running it still error like that

info
```
root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/reactpy-router# python3 --version
Python 3.10.6
```

**Comment by bobwatcherx** [comment]
now I have resolved the error by reinstalling the package .  is there a way to use it up to router parameters, router queries, and more details

root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/reactrouter-py# python3 main.py 
Traceback (most recent call last):
  File "/home/miop/belajar/reactrouter-py/main.py", line 3, in <module>
    from reactpy_router import Route, Link, bind
ImportError: cannot import name 'Link' from 'reactpy_router' (/usr/local/lib/python3.10/dist-packages/reactpy_router/__init__.py)

**Comment by rmorshea** [comment]
There's some WIP docs [here](https://github.com/rmorshea/reactpy-router/tree/add-docs#usage).

**Comment by bobwatcherx** [comment]
can the link be inserted into the button like this

```
html.button({
"to":"/about"
},"To about")

```
but not working or there is another way

**Comment by rmorshea** [comment]
Please start a discussion: https://github.com/reactive-python/reactpy-router/discussions
